[package]
name = "ruchess"
version = "0.1.0"
authors = ["Phil Hunt <cabalamat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
